### ISSUE TITLE
Boa Noite meu camarada

### ISSUE THREAD

**Issue by Mizael2019** [ialexanderbrito/be-the-hero#9]
Boa Noite meu camarada, queria uma ajuda sua se possível de um network para subir esse projeto teu no Netlify, estou batendo cabeça porque estou a fazer uma apresentação de automação de testes para minha empresa no Ramo de QA e já olhei de tudo que é jeito e não estou conseguindo, será que você topa uma ajuda. Te dou crédito quando for comentado sem duvidas.

Fico a disposição se quiser trocar ideia pelo zap ou discord, um abraço.

**Comment by ialexanderbrito** [comment]
Entra em contato comigo pelo discord
ialexanderbrito#3926

**Comment by Mizael2019** [comment]
Blz adicionei lá, não sou muito familiarizado com Discord desculpa qualquer coisa, a gente ta na correria do trampo imagino que tu tmb, mais quando tu puder tu aceita lá nós troca ideia, tamo junto meu mano obrigado.
